### ISSUE TITLE
[bug] Quickfixes do not show up on 1.2.0 branch.

### ISSUE THREAD

**Issue by FelixSchuSi** [runem/lit-analyzer#113]
Ever since [this commit](https://github.com/runem/lit-analyzer/commit/0f707962333765c4dfbb7181465c2d38a01a21ea), quickfixes do not show up anymore.

I found a workaround by setting the "code"-variable [here](https://github.com/runem/lit-analyzer/blob/1.2.0/packages/ts-lit-plugin/src/ts-lit-plugin/translate/translate-diagnostics.ts#L52) to a non-zero value.
This variable later gets handed to the language service as a property of an object of type Diagnostic.
Before the linked commit, this variable was set to 2322. I dont know is there was any reasoning behind this value.

This change makes error messages slightly uglier, since the variable shows up in error messages.

![new_error_message](https://i.imgur.com/NMjtwgs.jpg)

This is obviously not an ideal solution. Maybe someone else can find a better one.

**Comment by runem** [comment]
Thanks for reporting! I've been aware of this issue since changing code to 0 and have been trying to find a workaround. You are right, it seems like a non-0 code makes quick fixes work. The code 2322 is just the remains of the early days of lit-plugin and I just forgot to change it. I'm currently working with the theory that there is an additional Typescript Languageservice method called in order to request where quick fixes can be found, but it's difficult to find documentation for any of this :-) If I can't find another solution, I will add some meaningful codes for the rules so it's not always 1 (or 2322).

**Comment by FelixSchuSi** [comment]
Thanks for the info! Looking forward to the changes.

**Comment by runem** [comment]
So apparently I need to wrap "getSupportedCodeFixes" on the Typescript module (not the Language Service). This function should return which diagnostic codes can generate quick fixes. I initially tried to add 0 to the result and include code 0 on diagnostics, but that didn't work. It doesn't seem like there is a way to have codes fixes without having the number in parentheses. Therefore, I ended up with a solution where each rule has its own code. The fix is available on the 1.2.0 branch.
