### ISSUE TITLE
[lit-plugin] With 1.2.0 version autocomplete in CSS is broken

### ISSUE THREAD

**Issue by herberthobregon** [runem/lit-analyzer#120]
In this new version the autocomplete does not work correctly, I had to go back to version 1.1.10 in vscode.

If I try to put an example like
```css
div {
    disp...
}
```

It doesn't autocomplete,
![image](https://user-images.githubusercontent.com/6503845/87911539-0c79cc00-ca29-11ea-96ac-5fa633b29b78.png)

while in version 1.1.10 if it works correctly
![image](https://user-images.githubusercontent.com/6503845/87911420-d5a3b600-ca28-11ea-9dd2-dda65d075f63.png)

Many other css properties don't autocomplete correctly.

I checked it on the vscode of 3 other colleagues and the exact same thing happens.

> Thanks for your amazing work! If I can help you, don't hesitate to tell me

**Comment by runem** [comment]
I'm so sorry for the regression! I tested it extensively, but I think this slipped because I always force autocompletions with "ctlr + space" in the middle of some text, and this worked under most circumstances. However, it rarely worked if the autocompletion wasn't forced to set in.

I just uploaded a `.vsix` which you can download [here](https://drive.google.com/file/d/1RsiZworYfIgTBmmagzKcYFlf-2aorvbj/view?usp=sharing). It would be very helpful to me if you want to test if the problem has been fixed for you, and that it behaves as expected, You can install it like this:
<img width="477" alt="Screenshot 2020-07-20 at 19 47 11" src="https://user-images.githubusercontent.com/5372940/87969111-d2103d80-cac1-11ea-85ec-edfcc26bc24b.png">

**Comment by herberthobregon** [comment]
I'm still having the same problem, the CSS still doesn't auto-complete correctly :(

![image](https://user-images.githubusercontent.com/6503845/88012576-810b4400-cad7-11ea-9aa4-a1653eb9ca81.png)

**Comment by runem** [comment]
This is what I see when testing autocompletion. In this video I don't force auto completion at any point:

![autocompletion](https://user-images.githubusercontent.com/5372940/88058249-7c8c6d00-cb63-11ea-9ecf-68f0e090c2a9.gif)

I have a couple of things you can try if you have the time :-)
* Which version of VSCode are you using?
* Can you try to uninstall `lit-plugin` before installing the `.vsix` file? Maybe the new extension doesn't overwrite the existing one properly (because I didn't bump the version number of the `.vsix` file)
* Do you have some extensions that you think could interfere in the autocompletion process?

**Comment by herberthobregon** [comment]
It has worked! Thank you!
Completely closing VScode after installing (<kbd>⌘ + Q</kbd>) has successfully loaded the update sent to me by Google Drive!

**Comment by runem** [comment]
Great, I'm happy to hear that! I will publish the fix to the marketplace within a couple of days :-)
