### ISSUE TITLE
Add support to the color picker

### ISSUE THREAD

**Issue by abdonrd** [runem/lit-analyzer#30]
The color picker doesn't work

![feb-23-2019 00-13-09](https://user-images.githubusercontent.com/1007051/53276574-e2bb5900-36ff-11e9-9e1d-2f1c331b865d.gif)

**Comment by runem** [comment]
This feature has been implemented and I plan on including it in the next release of the extension :tada:

![colorpicker 2019-09-22 12_43_26](https://user-images.githubusercontent.com/5372940/65386028-b4a20400-dd36-11e9-821b-da23b7d577b3.gif)

**Comment by abdonrd** [comment]
When this new release? 😁

**Comment by runem** [comment]
At the moment I'm working extensively on finishing up this release, so ASAP. This is the version of the plugin that I'm testing for release: https://github.com/runem/lit-analyzer/suites/268960129/artifacts/135357 . I get some time this evening, so if I don't find any bugs, it will probably go live tonight. I'll keep you updated :-)

There have been a lot of changes to the architecture of the plugin, so I want to make sure that nothing breaks. I have also been adding a lot of tests In order to ensure shorter time between releases in the future :tada:

**Comment by abdonrd** [comment]
Sounds really great, thanks @runem! 👏

**Comment by runem** [comment]
Version 1.1.9 of [lit-plugin](https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin) has just been released :tada:

**Comment by herberthobregon** [comment]
CSS colors 🤩
