### ISSUE TITLE
Surprising error message for extra characters around non-string bindings

### ISSUE THREAD

**Issue by rictic** [runem/lit-analyzer#44]
We chatted about this issue in the comments of https://github.com/runem/lit-analyzer/pull/21 but it turns out I never filed a bug on it.

Consider code with (surprisingly common!) typos like:

```typescript
html`
<button @tap=${handler}" >
<button ?disabled=${handler}} >
`
```

In both cases there's an extra character after the binding which the user probably didn't intend, but which causes a somewhat confusing error message, as lit-analyzer thinks that we're passing a string to something that should be some other type. This is double confusing because it will usually do the right thing at runtime.

**Comment by runem** [comment]
How would you like lit-analyzer to respond to the typos? With a warning or with no warning? 

If it should respond with a warning I think we should add some checks for common patterns of typos (like [expression, '"'], [expression, '}']) and generate an understandable error message.

If it shouldn't respond with a warning I also think we should check for some common patterns and accept those specifically.

### Here's an overview of what's going on in the parser:

#### <button @tap=${handler}">
The attribute value is parsed as.
```js
{ kind: 'STRING', location: { start: 32, end: 31 }, value: '"' }
```
This seems like a parser bug (see location { start: 32, end: 31 }), because the parser gets confused that there isn't a corresponding start quote. It should be parsed as a 'mixed' instead: `[expression, '"']`. I'll make sure to fix the parser :-)

#### <button ?disabled=${handler}}>
```js
{ 
  kind: 'MIXED',
  location: { start: 66, end: 81 },
  values: [ <expression ast node>, "}" ]
}
```
Here the value is parsed correctly as a 'mixed' type: `[expression, "}"]`

### Here are the current diagnostics:

| Line | Column | Type    | Rule                         | Message                                          |
|------|--------|---------|------------------------------|--------------------------------------------------|
| 8    | 13     | `error` | no-noncallable-event-binding | You are setting up an event listener with a non-callable type '"""' |
| 9    | 13     | `error` | no-incompatible-type-binding | Type 'string' is not assignable to 'boolean'     |

**Comment by rictic** [comment]
> How would you like lit-analyzer to respond to the typos? With a warning or with no warning?

Yeah, I think this is totally a situation where a warning is warranted.

Not super surprising that a parser would get a little confused here, this is pretty deep into the edge case weeds.

Thanks for the super detailed overview of the issue!

**Comment by runem** [comment]
I'm thinking about adding a rule called something like `no-mixed-bindings`, enabled as default, that reports warnings on these patterns. I don't remember ever mixing multiple values in bindings in my own code (eg. `<input value="hello ${name}" />`), so I would think that this is more often unintended than intended. Maybe an exception could be added for `class` and `style` attributes (eg. `<input class="primary ${extraClasses}" />`).

What do you think?

**Comment by runem** [comment]
I just finished implementing the new rule on the [no-unexpected-mixed-binding](https://github.com/runem/lit-analyzer/tree/no-unexpected-mixed-binding) branch :-)

I ended up implementing it as you suggested above, and added `/` as a fourth control character. Now, `<button @tap=${handler}" >` will result in the error message "This binding is directly followed by an unmatched `"` which is probably unintended.".

**Comment by jrobinson01** [comment]
I just ran into this I believe, with the following code:
`@keypress=${event => this.onKeyPress(event)}/>`
moving the closing tag to the next line makes the error go away.

**Comment by runem** [comment]
With this feature (which will launch with the next version of lit-analyzer), your example will result in the following warning :-)

<img width="916" alt="Screenshot 2019-10-16 at 14 42 40" src="https://user-images.githubusercontent.com/5372940/66920326-54e00580-f023-11e9-847a-a39d0f466819.png">

**Comment by jrobinson01** [comment]
Why do we want a warning there? It makes sense if you're using a custom element that must have a closing tag, like:
```javascript
<my-element @event=${console.log}></my-element>
```
but if you're using a native element like input, it doesn't make sense (if your preference is to use the closing "/" style):
```javascript
<input @input=${console.log}/>
```

**Comment by runem** [comment]
The rule `no-unintended-mixed-binding` has been finished, and I fixed type checking of event listener bindings with mixed values at the same time (as mentioned above). Now `<input @input=${console.log}/>` will no longer warn that there is an unintended `/`, and it will correctly type check the expression. This also affects bindings like `<input @input="foo${console.log}bar" />`, where it now, correctly, only type checks the first expression of the mixed value.
