### ISSUE TITLE
Rollup necessity? 

### ISSUE THREAD

**Issue by 43081j** [runem/lit-analyzer#45]
out of interest, is there a reason you use rollup?

why not just build directly using `tsc` with CJS/ES2015+ as a target? (which would work fine in node)?

**Comment by runem** [comment]
I have also been thinking about removing rollup and just going with `tsc`, especially because there is a noticeable difference in speed between them.

**Here are my reasoning for introducing rollup:**
1. I planned on generating 2 separate bundles: "cli" and "analyzer".
2. The rollup setup merges Typescript declarations (for convenience)
3. I bake in the version of the analyzer when it's built see [constants.ts](https://github.com/runem/lit-analyzer/blob/master/packages/lit-analyzer/src/analyze/constants.ts#L19). This constant is used for debugging and for printing the version of the CLI.

I'm open for just using `tsc`, but we would have to either remove `VERSION´ or find another way to get the version of the package.

**Comment by justinfagnani** [comment]
Rollup will probably be a win for startup in Node, even if it's not required. Of course, an app can do that too.

From my side of the world, I'd love to see a pure modules distribution for use in something like: https://github.com/PolymerLabs/code-sample-editor

**Comment by justinfagnani** [comment]
In trying to [upgrade to modules](https://github.com/runem/lit-analyzer/issues/184) I'm running into a lot of problems related to ts-node and Ava and how test files import from source directly.

I think a lot of this should be simplified by just using `tsc` and having all tooling downstream from that only consume .js files.

Bundling can be done at the app entry points like the VS Code extension and the CLI, but the analyzer _library_ probably shouldn't be bundled. The TypeScript declarations shouldn't need to be merged either.

I'll put together a PR with this and migration to modules. It'll probably be large, but I think I have to try out all the changes together to see if they work.
