### ISSUE TITLE
Organising rules into individual modules

### ISSUE THREAD

**Issue by 43081j** [runem/lit-analyzer#46]
As part of giving this analyzer a go, i've been reading through the sources and what not.

One thing you could do IMO to tidy things up a lot and make the code base much easier to follow is introduce rules as their own concepts/modules.

What I mean is:

* Move all "rules" into their own file as functions which follow a new `RuleModule` type and are used like factories to create a `RuleVisitor` or some such thing
* Move all "reports" to the analyzer context
* Refactor the "analyzers" (e.g. `LitHtmlDocumentAnalyzer`) to instead load an array of rules and visit each node via them

I've already done most of this in a branch to see what would happen. So if you agree its a fair idea, ill push a PR up at some point when i get it all out of my head.

**Comment by runem** [comment]
Hi, thank you so much for helping me out. I would love to take a stab at this with you! :tada: 

Sorry, this comment ended up a bit longer than I planned.

I really agree there are a lot of places that need cleaning up. The latest addition to the code base was the concept of rules, and I also think the next logical step is to refactor it into separate rule modules. Lately I have only been focused on refactoring the project into a mono-repo, so unfortunately I haven't had that much time to clean up.

A couple of days ago I started refactoring into separate rule modules on a local branch. I just pushed them to the branch [rules](https://github.com/runem/lit-analyzer/tree/rules). I would love to join forces with you, and hopefully merge our work. It might not be possible to merge all of our changes automatically because of the amount of file changes in both, so some manual merging would be needed. On my branch I have only been working on migrating code that validate types. 

I'm really impressed by your work on https://github.com/runem/lit-analyzer/pull/47! I have read through your code, and here are my thoughts that I would love to discuss with you:

- In order to avoid unnecessary work, rules right now are "short-circuited", meaning that if a rule returns diagnostics for a given binding, no more rules are checked in the given context. This results in only one diagnostic per node, attribute & binding which is faster to execute and (I think) easier to understand because certain diagnostics don't make sense to show at the same time (eg. "You are binding a non-primitive type {foo: "bar"} in an attribute binding" and "Type '{foo: "bar"}' is not assignable to number"). Would it make sense to return: "LitDiagnostic[] | undefined" instead of adding "context.reports.push"? This way it would be possible to short-circuit by returning an array.

- I really like that you refactored type setup logic for validation assignments into "extractAttributeTypes"! One thing: I fear that there could come unnecessary many calls to this function as it's called for every type checking rule. Therefore I would prefer if was lifted to be called before the rule logic runs for a given binding.

- I cannot seem to find out where you check if rules are enabled before running them?

- It could also be interesting to think about "css" rules when doing this refactor. Right now there is only one css rule "no-invalid-css" but there might come more in the future.

**Here are some changed that I did on the 'rules' branch:**
- I adopted some things from your PR which I really liked.
- I added tests for each rule while I refactored to ensure that nothing breaks during the refactoring.
- Only rules for checking assignments have been refactored.
- More reliable type checking as now I directly extend the ts-simple-type type checking function.
- I updated "ts-simple-type" version, so "npm run bootstrap" must run again.
- In order to check "isRuleEnabled" before running the rule, the RuleModule type is an object literal and comes with a "name".
- Rules are provided by the "LitAnalyzerContext".
- Rules must return "LitDiagnostic[] | undefined". If returning "undefined" the next rule will be checked. If returning the array, the rule checks are "short-circuited".
- Rules are "short-circuited" per node, attribute and assignment. 
- There exists three rule hooks: "visitHtmlNode", "visitHtmlAttribute" and "visitHtmlAssignment".

**In the future I'm thinking about the following:**
- I'm thinking about renaming "AttrAssignment" to "Binding".
- There are some unnecessary properties on LitDiagnostic. For example, "kind" is unnecessary not that "source" has been added. In addition it might be too repetitive to set "severity", "source" and "location" from within a rule because these are already implied in the context.

I would love to discuss with you how to approach this refactor. Our work is similar on many points, so if you like my branch I would if you merge in your refactoring for "node" and "attribute" rules. Alternatively if you have concerns regarding my points I would love to hear them, so that we can discuss how best to proceed :-)

**Comment by 43081j** [comment]
The risk of windmilling in and refactoring everything before asking is exactly this 😂 didn't realise you were working on the same thing, but still well worth it to understand the codebase. Happy to try merge bits in here and there.

Rules are checked here:
https://github.com/runem/lit-analyzer/blob/17d63d014cb0440988921ffc6cd1927d2316457a/packages/lit-analyzer/src/analyze/document-analyzer/html/lit-html-document-analyzer.ts#L89-L91

The problem with moving the type extraction (typeA/typeB stuff) out of the rules is that they are no longer standalone/generic if you do. Ideally I think the analyzer should have little or no knowledge of what the rules do and only care that they implement a common interface (which ofc means then you can't have any logic in the analyzer its self before calling the rules, as you would be removing control from them).

Lets say you have a rule which does _not_ want to do those checks, you end up in some messy situation where you'll add some kind of workaround to get it working. whereas if rules are where the logic lives, its upto them what they can do.

a solution could be to either cache the type extraction results, or to have a middle-man visitor which calls something like `enterAssignment` rather than `enterHtmlAttribute`.

The short circuiting should really happen at the analyzer level I think. as in, before executing the next visitor, check if there are any reports (for the given node) and don't execute the next one if there is. doesn't sound like it should be difficult to implement. I would do this instead of having non-void return types for visitors really, and maybe even introduce a `context.report(...)` method. 

ill have a look around your branch if i get chance tomorrow.

**Comment by runem** [comment]
I'm really sorry, I also think it's partly on me because I haven't been building that branch in the public 🙉 I will make sure to push future WIP work as quickly and often as possible!

I hope you learned a lot about the code base! I would love to do future work on lit-analyzer in collaboration with you if you want to :-)

**Rule names**
On your branch, the rule source is set both within the rule itself (on diagnostics) and in [lit-html-document-analyzer](https://github.com/runem/lit-analyzer/blob/17d63d014cb0440988921ffc6cd1927d2316457a/packages/lit-analyzer/src/analyze/document-analyzer/html/lit-html-document-analyzer.ts#L46) mapped to the rule logic. I like the map, but I fear that the rule names could get out of sync because it's repeated. What do you think about having the 'source of truth' of the rule name defined only in the individual rule modules, thus changing 'defaultRules' to an array instead of object literal? If did that on the 'rules' branch.

**Type extraction**
I see what you mean. I agree that it's a bit awkward if rules for checking assignability have special treatment. I have now changed the responsibility on the `rules` branch so that each rule is responsible for extracting types (it was interesting to see that 2 rules didn't need the types). However, I still think it would be positive to introduce some kind of caching here.

Now the `RuleModule` looks like this:
https://github.com/runem/lit-analyzer/blob/rules/packages/lit-analyzer/src/analyze/document-analyzer/html/diagnostic/rules/rule-module.ts#L8-L13

**Short circuiting**
I would love to see an addition to the 'rules' branch using a callback/push and not return. Be aware that I think it would make best sense to add the "callback/reports/diagnostics array" to the [request type](https://github.com/runem/lit-analyzer/blob/17d63d014cb0440988921ffc6cd1927d2316457a/packages/lit-analyzer/src/analyze/lit-analyzer-context.ts#L29) and not to `context`. `context` should be seen as the 'global context' while `request` should be seen as the temporary context for the current language service request (if that makes sense).  

**Other**
I see that you placed the rules directory in `src`. Right now rules on the 'rules' branch are hidden deep within `lit-analyzer/src/analyze/document-analyzer/html/diagnostic/rules`, but I plan on moving them to the `src` directory tomorrow :+1:

**Comment by 43081j** [comment]
No need being sorry its all good fun, got me active again so some good came from it 😆 

### Rule names

Don't mind the `defaultRules` property, I basically left it there as placeholder until we figured out how we should pass rules in.

IMO we should follow what linters do roughly so people can pick up the config easily. This means having an object in your config like so:

```json
{
  "rules": {
    "rule-1": "error",
    "rule-2": "warn",
    "rule-3": "off"
  }
}
```

If we kept some kind of lazy evaluated map hanging around of all available rules (`readonly Map<RuleName, RuleModule>`), we could then pretty easily iterate over the user's configured rules and execute the associated modules.

### Rule modules

I still would opt for having a `void` return type in modules to stick to the usual visitor pattern, in that you'd expect either of these in a visitor:

```
visit(Node): Node
visit(Node): void
```

because we're not transforming nodes, we should just have `void` IMO.

it makes things concise to return the diagnostics because you can easily just concat them or dump them in an array, but i'd rather than be done by a `context.report({ ... })` of some sort.

upto you really though as its preference more than anything.

### Short circuiting

For sake of consistency with what other transformers/linters/etc do, it would be worthwhile keeping it called `context` but definitely putting the reports on the request instead.

**Comment by runem** [comment]
### Rule names

I actually modelled this part of the config after eslint. Therefore rules are configurable like this:

```json
{
  "rules": {
    "no-unknown-attribute": "error",
    "no-unknown-event": "warn",
    "no-unknown-property": "off"
  }
}
```

Remember that the order of rules is important. For example, we want `no-invalid-directive-binding` to run before `no-incompatible-type-binding` because I think it's better to know that a directive is used incorrectly than that the return type of the directive is incompatible. 

Using a `Map<RuleName, RuleModule>` sound fine, as long as we control the insertion order of the rules. However an array like `RuleModule[]` might better communicate that the order matters. Therefore I'm a bit torn on array vs map for keeping available rules internally, but all in all both solutions would be fine to me. 

### Reporting diagnostics

I like the `context.report({...})` solution and think we should go with that as long as we handle the short-circuiting :-)

### Rule modules

In general I'm very :+1: for getting as close as eslint does it! 

Note that we might need to reinitialise all activated rules per call to "getDiagnostics" because the `sourceFile` and `document` on the "context" object are new per call. If you don't think this matters I think it would be fine to change RuleModule's to be factories generating a RuleVisitor. 

### Context
I'm on board with renaming "request" to "context", but then I think the existing "context" should be renamed to something like "baseContext":

 - `interface LitAnalyzerContext` --> `interface LitAnalyzerBaseContext`

 - `interface LitAnalyzerRequest extends LitAnalyzerContext` -->  `interface LitAnalyzerContext extends LitAnalyzerBaseContext`

If so, I would like to rename these as I think there are a lot of places I need to rename 👍 

### Other

I lifted rules to `lit-analyzer/src/rules` and there are now 90 tests testing all rules. Rules for nodes and attributes have not been refactored out to rule modules yet. I might get some time tomorrow to do it. If you want to help with any of the above, you are very welcome! :-)

**Comment by 43081j** [comment]
### Rule config

I think you should maybe ask yourself why and if order should matter in this case.

Imagine every rule is kinda like a pure function, standalone and is guaranteed to work out of context against any individual file. If we enforce some kind of ordering, i can see there being a risk of 'flakiness' as time goes on and more rules are added (with implicit dependencies scattered around).

Maybe a rule module could have a `priority` or some such thing which we automatically order by, rather than a specific rule order (so it becomes configurable). I can see your reasoning so the ordering isn't a bad idea in reality, so this seems like a good compromise where you can keep some kind of order while not caring what the actual array order is initially (or what rules are loaded).

### Diagnostics

Yep with a `report` method we can pretty easily abstract how reports/diagnostics are processed and kept around. We could pretty much then just check after each visitor (rule) is called, if the current node already has reports and short-circuit if it does.

### context

exactly what i was hoping for, a base context and the actual context 👍 

### Branch stuff

as for my branch/PR, do you want me to close it (but ill keep the branch around)?

if there's anything in particular you like from it just cherry pick or copy it over, as you seem to have your branch mostly aligned with what was in my head now.

when i get chance ill read the diff of your branch and let you know if theres anything else i have to suggest

**Comment by 43081j** [comment]
ah and yes i still think a factory or a class would be a little cleaner than a collection of statics.

even if we create an instance per file, it means we only need one instance for the whole file rather than per node. and it leaves space for rules to have locals/state.

**Comment by runem** [comment]
### Rule config

I agree that rules should be entirely self contained. Your suggestion with `priority` to control the order of rules would be a good solution I think. The `priority` could be a property on RuleModule alongside  `name`. 

### Factories

This also means that we would need to keep a cache of `RuleVisitor`'s perhaps in a `WeakMap` keyed by `SourceFile`. 

I don't think we would have to create new instances per file, - we would have to initialize and cache rules for a given file each time the file changes because `SourceFile` and `Program` are immutable data structures and will therefore be unique per call to `getDiagnostics` (implied that the method is only called once per file change which the language service does). 

If we end up reinitializing rules per file change, the locals/state would would only live for one call, and then we would initialize a new set of `RuleVisitor` for the next call. 

I fear it might end up consuming unnecessary memory for very little gain. 
 
Based on the above I like better that the `RuleModule` is a object with `name`, `priority` and 3 pure functions like `visitHtmlNode`, `visitHtmlAttribute` and `visitHtmlAssignment` each taking a node/attribute/assignment as 1st parameter and context as 2nd parameter. 

### Branch/PR

I'll make a PR with the changes now. I think we should close your PR and work on this new one :-)
 
If you like I would love to see `context.report({...})` cherry picked from your branch (with included short-circuiting). 

 2. It would also be awesome to see refactored RuleModules for node and attribute diagnostics. However I get some time later today so if you haven't started this I think I will finished these RuleModules by today.

**More stuff that we talk about that you are very welcome to take look at:**

 3. `priority` on RuleModule
 4. `Map<RuleName, RuleModule>` on BaseContext (right now it's an array called `rules`)

**I would like to build the following:**

 5. `LitAnalyzerRequest` --> `LitAnalyzerContext` 
 6. Caching type extraction
 7. Document code
 8. More tests

**Other**

 9. RuleModule as factory creating RuleVisitor (I still think we need to discuss and agree on this one)

Again, I'm very grateful for you helping this project, so thank you! :-)

**Comment by runem** [comment]
FYI, I'll start refactoring functionality for `no-unclosed-tag`, `no-unknown-tag-name`, `no-missing-import`, `no-unknown-slot`, `no-unknown-attribute`, `no-unknown-property` and `no-unknown-event` into RuleModules now :-)
