### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by elazutkin-dynata** [runem/lit-analyzer#52]
- Issue Type: `Performance`
- Extension Name: `lit-plugin`
- Extension Version: `1.1.6`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.37.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/eugene.lazutkin/runem.lit-plugin-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by runem** [comment]
Hi Eugene, thank you so much for reporting this issue!

I have also seen high CPU usage on one of my own projects with a lot of project files (2000+). How many files are included in your project? Would it also be possible for you to enable verbose logging from the extension settings and share with me the `lit-plugin.log` file? 

This issue is high priority to me and will keep you updated here :-)

**Comment by elazutkin-dynata** [comment]
The project I am working on is not very big. I think it is less than 100 files (if not counting `node_modules`). I'll try to enable the verbose logging.

**Comment by runem** [comment]
I've made some changes to `ts-simple-type` that greatly improves performance. We've seen up to 15x speed improvements. You can read a more detailed description in this related issue: https://github.com/runem/lit-analyzer/issues/90. The improvements can be found in this PR: https://github.com/runem/lit-analyzer/pull/112

If you want to, you can try out the beta version of lit-plugin by installing this vsix file: https://github.com/runem/lit-analyzer/suites/880715423/artifacts/10350981. It would be really interesting for me to know how much performance has improved for you if you would like to try it out :-)
