### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by ashubham** [runem/lit-analyzer#58]
![image](https://user-images.githubusercontent.com/6115911/66419283-adc2f480-e9b8-11e9-9d25-a7ad9bf8d693.png)

This is coming with the latest version of typescript `3.7.0`

**Comment by runem** [comment]
Hi, thanks for opening an issue :)

I have some questions in order to easier solve the problem.

* First of all, you are running with the latest beta version `typescript@3.7.0-beta`, right?
* Are you using the CLI or are you using lit-analyzer through the js API?
* Are you using a flat install of dependencies? What's the output of running `npm ls typescript`?

**Comment by runem** [comment]
I was able to reproduce and fix the problem with this commit https://github.com/runem/web-component-analyzer/commit/05900d85e115e5f908dac86729f85cb57cfd238d :tada:
