### ISSUE TITLE
no-incompatible-type-binding on HTML role Attribute too restrictive

### ISSUE THREAD

**Issue by dgoogles** [runem/lit-analyzer#89]
If we specify multiple roles on an html element like 

`<div role="button listitem"></div> `

lit-analyzer surfaces an error because it tries to match the role attribute to exactly ONE role. However, the spec allows for a list of roles. I tried to dig into the code a little bit and it seems lit-analyzer gets part of this logic from `vscode-html-languageservice` But perhaps is being too strict or using it incorrectly.

**Comment by runem** [comment]
Thanks for reporting this bug!

In order to fix this I have to come op with a solution where the "whitespace-separated-string-literal-union"-type can be type checked using both a custom type and custom type checking logic. 

This will have to include these 2/3 attributes (there might be more):
- `controlslist` on `<video>`: https://wicg.github.io/controls-list/html-output/multipage/embedded-content.html#attr-media-controlslist
- `role` attribute: https://www.w3.org/TR/role-attribute/
- `class` attribute (might not be relevant): https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#classes

The type checker will have to split the value by whitespace, check that there are no duplicates and make sure that all values in the list are assignable to the string literal union.

**Comment by runem** [comment]
I just finished adding support for the `role` and `controlslist` attributes. I will close this issue when the fix has been released.

![list-type-checking](https://user-images.githubusercontent.com/5372940/86970064-153be980-c16f-11ea-978a-98a66306125c.gif)

**Comment by scola84** [comment]
Would it be possible to apply this to user-defined attributes too?
